[build]
  base = "aaronHur-support-sanctuary-main"
  command = "npm run build"
  publish = "dist"

# SPA fallback so client routes resolve correctly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
